openapi: 3.0.0
info:
  title: Fazi Integration API
  version: 1.0.0
  description: >
    This API contains a single endpoint that allows external partners to request a dynamically generated URL for launching a game session. All parameters are passed via URL-encoded query string values.

servers:
  - url:  https://integration.fazi.rs

paths:
  /Home/GetDynamicURL:
    get:
      summary: Generates a dynamic game launch URL
      description: >
        Accepts a list of query parameters and returns a dynamic URL that can be used 
        to launch a game. All parameters must be URL-encoded.
      parameters:
        - name: portalCode
          in: query
          description: Unique code identifying portal (FAZI provided).
          required: true
          schema:
            type: string
        - name: token
          in: query
          description: One time session token unique for player, used only for authentication.
          required: true
          schema:
            type: string
        - name: gameName
          in: query
          description: Name of the game to be launched.
          required: true
          schema:
            type: string
        - name: playerID
          in: query
          description: Unique code identifier of the player.
          required: false
          schema:
            type: string
        - name: integrationType
          in: query
          description: Internal unique identifier of integrataon.
          required: false
          schema:
            type: integer
        - name: moneyType
          in: query
          description: 0 if player chooses to play for free and 1 if player plays for real money.
          required: false
          schema:
            type: integer
        - name: lobbyUrl
          in: query
          description: URL where the player is redirected after closing the game.
          required: false
          schema:
            type: string
            format: uri
        - name: languageCode
          in: query
          description: Language ISO code .
          required: false
          schema:
            type: string
        - name: currency
          in: query
          description: Currency ISO code.
          required: false
          schema:
            type: string
        - name: roomID
          in: query
          description: Unique identifier of the room.
          required: false
          schema:
            type: string
        - name: countryCode
          in: query
          description: Country ISO3 code where the game is running.
          required: false
          schema:
            type: string
            minLength: 3
            maxLength: 3

      responses:
        '200':
          description: Dynamic URL successfully generated
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: OK
                  launchUrl:
                    type: string
                    format: uri
                    example: https://gameserver-store-ms.fazi.rs/Home/IntegrationGameLaunch/omegamozzartbetrsd?moneyType=0&currency=RSD&gameName=WildHot40&integrationType=78&languageCode=eng&platform=desktop

        '401':
          description: Unauthorized – invalid credentials
          content:
            application/json:
              schema:
                type: object
                properties:
                  errorCode:
                    type: string
                    example: UNAUTHORIZED
                  errorMessage:
                    type: string
                    example: The client is not authorized for this action.
                  correlationId:
                    type: string
                    format: uuid
                    example: 5915d539-6107-48bb-954d-6cb049f8e662
                  timestamp:
                    type: string
                    format: date-time
                    example: 2025-06-20T13:38:55.623+00:00

        '400':
          description: Bad request – required parameters are missing or invalid
          content:
            application/json:
              schema:
                type: object
                properties:
                  errorCode:
                    type: string
                    example: RequestParameterInvalidType
                  errorMessage:
                    type: string
                    example: One or more request parameters have invalid type.
                  correlationId:
                    type: string
                    format: uuid
                    example: 5915d539-6107-48bb-954d-6cb049f8e662
                  timestamp:
                    type: string
                    format: date-time
                    example: 2025-06-20T13:38:55.623+00:00

        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  errorCode:
                    type: string
                    example: GENERAL_ERROR
                  errorMessage:
                    type: string
                    example: General server error. Please contact Fazi support.
                  correlationId:
                    type: string
                    format: uuid
                    example: 5915d539-6107-48bb-954d-6cb049f8e662
                  timestamp:
                    type: string
                    format: date-time
                    example: 2025-06-20T13:38:55.623+00:00


components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
